---
title: "Liberia Coverage Assessment of Direct Nutrition Interventions"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
if(!require(remotes)) install.packages("remotes")
if(!require(liberia)) install_github("validmeasures/liberia")
if(!require(liberiaData)) install_github("validmeasures/liberiaData")
if(!require(gstat)) install.packages("gstat")
if(!require(rgdal)) install.packages("rgdal")
if(!require(rgeos)) install.packages("rgeos")
if(!require(raster)) install.packages("raster")
if(!require(RColorBrewer)) install.packages("RColorBrewer")
if(!require(ggplot2)) install.packages("ggplot2")

#
# Create Mapbox base layer objects for leaflet mapping
#
mapbox.satellite <- "https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v10/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.street    <- "https://api.mapbox.com/styles/v1/mapbox/streets-v10/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.dark      <- "https://api.mapbox.com/styles/v1/mapbox/dark-v9/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.light     <- "https://api.mapbox.com/styles/v1/mapbox/light-v9/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.moonlight <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj3nban30001z2rpahc10c9ef/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.northstar <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj4ke832y4sng2spe2ds4fs55/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.standard  <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj5di36jn0gxg2rphjn3yetpt/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.decimal   <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj5ms1akt3pbi2smtcewsex9m/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.terminal  <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj6g0tzbd30kc2sph2wyh666m/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"

monrovia <- subset(liberia::districts, admin2Name == "Greater Monrovia")
gmLng1 <- bbox(monrovia)[1, 1]
gmLat1 <- bbox(monrovia)[2, 1]
gmLng2 <- bbox(monrovia)[1, 2]
gmLat2 <- bbox(monrovia)[2, 2]

grandBassa <- subset(liberia::counties, admin1name == "Grand Bassa")
gbLng1 <- bbox(grandBassa)[1, 1]
gbLat1 <- bbox(grandBassa)[2, 1]
gbLng2 <- bbox(grandBassa)[1, 2]
gbLat2 <- bbox(grandBassa)[2, 2]
```

Urban Montserrado
================================================================================

Row {.tabset .tabset-fade}
--------------------------------------------------------------------------------

### IFA

```{r ifaGM}
library(leaflet)

covHex <- gmHexGrid
covHex@data <- data.frame(covHex@data, ifaInt)

pal <- colorNumeric(palette = brewer.pal(n = 10, name = "RdYlGn"),
                    domain = c(0,1))

leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gmLng1, lat1 = gmLat1,
            lng2 = gmLng2, lat2 = gmLat2) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$ifa1),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$ifa1),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$ifa1 * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Attended ANC"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$ifa2),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$ifa2),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$ifa2 * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Know/heard of IFA"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$ifa3),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$ifa3),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$ifa3 * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Received/purchased IFA"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$ifa4),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$ifa4),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$ifa4 * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Took IFA"
	) %>%
  addLegend(pal = pal, 
    opacity = 0.7,
    values = c(0,1),
		position = "bottomleft", 
		labFormat = labelFormat(suffix = "%", transform = function(x) x * 100),
		layerId = "legend") %>%
  addLayersControl(
		baseGroups = c("Attended ANC", "Know/heard of IFA", "Received/purchased IFA", "Took IFA"),
		position = "topleft",
		options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE)
	)
```

### IYCF

```{r iycfGM}
library(leaflet)

covHex <- gmHexGrid
covHex@data <- data.frame(covHex@data, iycfInt)

pal <- colorNumeric(palette = brewer.pal(n = 10, name = "RdYlGn"),
                    domain = c(0,1))

leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gmLng1, lat1 = gmLat1,
            lng2 = gmLng2, lat2 = gmLat2) %>%
    addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$icf1),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$icf1),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$icf1 * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Know/heard about IYCF counselling"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$icf2),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$icf2),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$icf2 * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Attended IYCF counselling"
	) %>%
  addLegend(pal = pal, 
    opacity = 0.7,
    values = c(0,1),
		position = "bottomleft", 
		labFormat = labelFormat(suffix = "%", transform = function(x) x * 100),
		layerId = "legend") %>%
  addLayersControl(
		baseGroups = c("Know/heard about IYCF counselling", "Attended IYCF counselling"),
		position = "topleft",
		options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE)
	)
```

### MNP

```{r mnpGM}
library(leaflet)

covHex <- gmHexGrid
covHex@data <- data.frame(covHex@data, mnpInt)

pal <- colorNumeric(palette = brewer.pal(n = 10, name = "RdYlGn"),
                    domain = c(0,1))

leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gmLng1, lat1 = gmLat1,
            lng2 = gmLng2, lat2 = gmLat2) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$mnp1),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$mnp1),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$mnp1 * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Know/heard about MNP"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$mnp2),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$mnp2),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$mnp2 * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Received/purchased MNP"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$mnp3),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$mnp3),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$mnp3 * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Gave MNP to child"
	) %>%
  addLegend(pal = pal, 
    opacity = 0.7,
    values = c(0,1),
		position = "bottomleft", 
		labFormat = labelFormat(suffix = "%", transform = function(x) x * 100),
		layerId = "legend") %>%
  addLayersControl(
		baseGroups = c("Know/heard about MNP", "Received/purchased MNP", "Gave MNP to child"),
		position = "topleft",
		options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE)
	)
```

### Vitamin A

```{r vitGM}
library(leaflet)

covHex <- gmHexGrid
covHex@data <- data.frame(covHex@data, vitInt)

pal <- colorNumeric(palette = brewer.pal(n = 10, name = "RdYlGn"),
                    domain = c(0,1))

leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gmLng1, lat1 = gmLat1,
            lng2 = gmLng2, lat2 = gmLat2) %>%
    addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$vit1),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$vit1),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$vit1 * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Child received vitamin A in the past 6 months"
	) %>%
  addLegend(pal = pal, 
    opacity = 0.7,
    values = c(0,1),
		position = "bottomleft", 
		labFormat = labelFormat(suffix = "%", transform = function(x) x * 100),
		layerId = "legend") %>%
  addLayersControl(
		baseGroups = c("Child received vitamin A in the past 6 months"),
		position = "topleft",
		options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE)
	)
```

### Nutrition Screening

```{r screenGM}
library(leaflet)

covHex <- gmHexGrid
covHex@data <- data.frame(covHex@data, screenInt)

pal <- colorNumeric(palette = brewer.pal(n = 10, name = "RdYlGn"),
                    domain = c(0,1))

leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gmLng1, lat1 = gmLat1,
            lng2 = gmLng2, lat2 = gmLat2) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$weight.screen),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$weight.screen),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$weight.screen * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Child weight measured in past month"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$height.screen),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$height.screen),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$height.screen * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Child height measured in past month"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$muac.screen),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$muac.screen),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$muac.screen * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Child MUAC measured in past month"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$oedema.screen),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$oedema.screen),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$oedema.screen * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Child checked for oedema in past month"
	) %>%
  addLegend(pal = pal, 
    opacity = 0.7,
    values = c(0,1),
		position = "bottomleft", 
		labFormat = labelFormat(suffix = "%", transform = function(x) x * 100),
		layerId = "legend") %>%
  addLayersControl(
		baseGroups = c("Child weight measured in past month", 
		               "Child height measured in past month", 
		               "Child MUAC measured in past month", 
		               "Child checked for oedema in past month"),
		position = "topleft",
		options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE)
	)
```

### CMAM

```{r cmamGM}
library(leaflet)

covHex <- gmHexGrid
covHex@data <- data.frame(covHex@data, cmamInt)

pal <- colorNumeric(palette = brewer.pal(n = 10, name = "RdYlGn"),
                    domain = c(0,1))

leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gmLng1, lat1 = gmLat1,
            lng2 = gmLng2, lat2 = gmLat2) %>%
    addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$cf),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$cf),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$cf * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "CMAM Case-finding Effectiveness"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$tc),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$tc),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$tc * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "CMAM Treatment Coverage"
	) %>%
  addLegend(pal = pal, 
    opacity = 0.7,
    values = c(0,1),
		position = "bottomleft", 
		labFormat = labelFormat(suffix = "%", transform = function(x) x * 100),
		layerId = "legend") %>%
  addLayersControl(
		baseGroups = c("CMAM Case-finding Effectiveness", "CMAM Treatment Coverage"),
		position = "topleft",
		options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE)
	)
```

### Stunting

```{r stuntGM}
library(leaflet)

covHex <- gmHexGrid
covHex@data <- data.frame(covHex@data, anthroInt)

pal <- colorNumeric(palette = rev(brewer.pal(n = 10, name = "RdYlGn")),
                    domain = c(0,
                               max(anthroInt$global.haz, 
                                   anthroInt$moderate.haz, 
                                   anthroInt$severe.haz)))

leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gmLng1, lat1 = gmLat1,
            lng2 = gmLng2, lat2 = gmLat2) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$global.haz),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$global.haz),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$global.haz * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Global stunting"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$moderate.haz),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$moderate.haz),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$moderate.haz * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Moderate stunting"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$severe.haz),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$severe.haz),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$severe.haz * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Severe stunting"
	) %>%
  addLegend(pal = pal, 
    opacity = 0.7,
    values = c(0,
               max(anthroInt$global.haz, 
                   anthroInt$moderate.haz, 
                   anthroInt$severe.haz)),
		position = "bottomleft", 
		labFormat = labelFormat(suffix = "%", transform = function(x) x * 100),
		layerId = "legend") %>%
  addLayersControl(
		baseGroups = c("Global stunting", "Moderate stunting", "Severe stunting"),
		position = "topleft",
		options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE)
	)
```


### Underweight

```{r underweightGM}
library(leaflet)

pal <- colorNumeric(palette = rev(brewer.pal(n = 10, name = "RdYlGn")),
                    domain = c(0,
                               max(anthroInt$global.waz, 
                                   anthroInt$moderate.waz, 
                                   anthroInt$severe.waz)))

leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gmLng1, lat1 = gmLat1,
            lng2 = gmLng2, lat2 = gmLat2) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$global.waz),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$global.waz),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$global.waz * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Global underweight"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$moderate.waz),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$moderate.waz),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$moderate.waz * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Moderate underweight"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$severe.waz),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$severe.waz),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$severe.waz * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Severe underweight"
	) %>%
  addLegend(pal = pal, 
    opacity = 0.7,
    values = c(0,
               max(anthroInt$global.waz, 
                   anthroInt$moderate.waz, 
                   anthroInt$severe.waz)),
		position = "bottomleft", 
		labFormat = labelFormat(suffix = "%", transform = function(x) x * 100),
		layerId = "legend") %>%
  addLayersControl(
		baseGroups = c("Global underweight", "Moderate underweight", "Severe underweight"),
		position = "topleft",
		options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE)
	)
```

### Wasting (WHZ)

```{r whzGM}
library(leaflet)

pal <- colorNumeric(palette = rev(brewer.pal(n = 10, name = "RdYlGn")),
                    domain = c(0,
                               max(anthroInt$gam.whz, 
                                   anthroInt$mam.whz, 
                                   anthroInt$sam.whz)))

leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gmLng1, lat1 = gmLat1,
            lng2 = gmLng2, lat2 = gmLat2) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$gam.whz),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$gam.whz),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$gam.whz * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Global wasting by WHZ"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$mam.whz),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$mam.whz),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$mam.whz * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Moderate wasting by WHZ"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$sam.whz),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$sam.whz),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$sam.whz * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Severe wasting by WHZ"
	) %>%
  addLegend(pal = pal, 
    opacity = 0.7,
    values = c(0,
               max(anthroInt$gam.whz, 
                   anthroInt$mam.whz,
                   anthroInt$sam.whz)),
		position = "bottomleft", 
		labFormat = labelFormat(suffix = "%", transform = function(x) x * 100),
		layerId = "legend") %>%
  addLayersControl(
		baseGroups = c("Global wasting by WHZ", "Moderate wasting by WHZ", "Severe wasting by WHZ"),
		position = "topleft",
		options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE)
	)
```


### Wasting (MUAC)

```{r muacGM}
library(leaflet)

pal <- colorNumeric(palette = rev(brewer.pal(n = 10, name = "RdYlGn")),
                    domain = c(0,
                               max(anthroInt$gam.muac, 
                                   anthroInt$mam.muc, 
                                   anthroInt$sam.muac)))

leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gmLng1, lat1 = gmLat1,
            lng2 = gmLng2, lat2 = gmLat2) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$gam.muac),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$gam.muac),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$gam.muac * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Global wasting by MUAC"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$mam.muac),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$mam.muac),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$mam.muac * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Moderate wasting by MUAC"
	) %>%
  addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$sam.muac),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$sam.muac),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$sam.muac * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Severe wasting by MUAC"
	) %>%
  addLegend(pal = pal, 
    opacity = 0.7,
    values = c(0,
               max(anthroInt$gam.muac, 
                   anthroInt$mam.muc,
                   anthroInt$sam.muac)),
		position = "bottomleft", 
		labFormat = labelFormat(suffix = "%", transform = function(x) x * 100),
		layerId = "legend") %>%
  addLayersControl(
		baseGroups = c("Global wasting by MUAC", "Moderate wasting by MUAC", "Severe wasting by MUAC"),
		position = "topleft",
		options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE)
	)
```

### Oedema

```{r oedemaGM}
library(leaflet)

pal <- colorNumeric(palette = rev(brewer.pal(n = 10, name = "RdYlGn")),
                    domain = c(0, max(anthroInt$oedema)))

leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gmLng1, lat1 = gmLat1,
            lng2 = gmLng2, lat2 = gmLat2) %>%
    addPolygons(
	  data = covHex,
	  fillColor = pal(covHex$oedema),
	  weight = 1,
	  opacity = 1,
	  color = pal(covHex$oedema),
	  dashArray = "",
	  fillOpacity = 0.7,
	  highlight = highlightOptions(
		  weight = 3,
		  color = "#666",
		  dashArray = "",
		  fillOpacity = 0.7,
		  bringToFront = TRUE),
	  label = paste(round(covHex$oedema * 100, digits = 1), "%", sep = ""),
	  labelOptions = labelOptions(
		  style = list("font-weight" = "normal", padding = "3px 8px"),
		  textsize = "12px",
		  direction = "auto"),
	  group = "Oedema"
	) %>%
  addLegend(pal = pal, 
    opacity = 0.7,
    values = c(0, max(anthroInt$oedema)),
		position = "bottomleft", 
		labFormat = labelFormat(suffix = "%", transform = function(x) x * 100),
		layerId = "legend") %>%
  addLayersControl(
		baseGroups = c("Oedema"),
		position = "topleft",
		options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE)
	)
```


Grand Bassa
================================================================================

Row {.tabset .tabset-fade}
--------------------------------------------------------------------------------
 
### IFA

```{r ifaGB}
leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gbLng1, lat1 = gbLat1,
            lng2 = gbLng2, lat2 = gbLat2)
```

### IYCF

```{r iycfGB}
leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gbLng1, lat1 = gbLat1,
            lng2 = gbLng2, lat2 = gbLat2)
```

### MNP

```{r mnpGB}
leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gbLng1, lat1 = gbLat1,
            lng2 = gbLng2, lat2 = gbLat2)
```

### Vitamin A

```{r vitGB}
leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gbLng1, lat1 = gbLat1,
            lng2 = gbLng2, lat2 = gbLat2)
```

### Nutrition Screening

```{r screenGB}
leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gbLng1, lat1 = gbLat1,
            lng2 = gbLng2, lat2 = gbLat2)
```

### CMAM

```{r cmamGB}
leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gbLng1, lat1 = gbLat1,
            lng2 = gbLng2, lat2 = gbLat2)
```

### Stunting

```{r stuntGB}
leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gbLng1, lat1 = gbLat1,
            lng2 = gbLng2, lat2 = gbLat2)
```

### Underweight

```{r underweightGB}
leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gbLng1, lat1 = gbLat1,
            lng2 = gbLng2, lat2 = gbLat2)
```

### Wasting (WHZ)

```{r whzGB}
leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gbLng1, lat1 = gbLat1,
            lng2 = gbLng2, lat2 = gbLat2)
```

### Wasting (MUAC)

```{r muacGB}
leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gbLng1, lat1 = gbLat1,
            lng2 = gbLng2, lat2 = gbLat2)
```

### Oedema

```{r oedemaGB}
leaflet() %>%
  addTiles(urlTemplate = mapbox.street,
    attribution = "Maps by <a href='http://www.mapbox.com/'>Mapbox</a>"
  ) %>%
  fitBounds(lng1 = gbLng1, lat1 = gbLat1,
            lng2 = gbLng2, lat2 = gbLat2)
```